### ISSUE TITLE
cudnn build failure 

### ISSUE THREAD

**Issue by Violetit** [liuzhengzhe/One-Thing-One-Click#1]
Hi, @liuzhengzhe 

cmake fails to identify cudnn version in the step: `python setup.py bdist_wheel`
Could you help to solve this issue?
```
running bdist_wheel
running build
running build_py
running build_ext
/data/li/One-Thing-One-Click/3D-U-Net/lib/spconv/build/lib.linux-x86_64-3.7
Release
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /cm/shared/apps/cuda10.1/toolkit/10.1.243/bin/nvcc
-- Caffe2: CUDA toolkit directory: /cm/shared/apps/cuda10.1/toolkit/10.1.243
-- Caffe2: Header version is: 10.1
-- Could NOT find CUDNN (missing: CUDNN_LIBRARY_PATH CUDNN_INCLUDE_PATH) 
CMake Warning at /home/li/.conda/envs/tia37/lib/python3.7/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:109 (message):
  Caffe2: Cannot find cuDNN library.  Turning the option off
Call Stack (most recent call first):
  /home/li/.conda/envs/tia37/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/li/.conda/envs/tia37/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:24 (find_package)


-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX;7.5;7.5+PTX
-- Added CUDA NVCC flags for: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_70,code=compute_70;-gencode;arch=compute_75,code=compute_75
CMake Error at /home/li/.conda/envs/tia37/lib/python3.7/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:96 (message):
  Your installed Caffe2 version uses cuDNN but I cannot find the cuDNN
  libraries.  Please set the proper cuDNN prefixes and / or install cuDNN.
Call Stack (most recent call first):
  /home/li/.conda/envs/tia37/lib/python3.7/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:24 (find_package)


-- Configuring incomplete, errors occurred!
See also "/data/li/One-Thing-One-Click/3D-U-Net/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
See also "/data/li/One-Thing-One-Click/3D-U-Net/lib/spconv/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    zip_safe=False,
  File "/home/li/.conda/envs/tia37/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/li/.conda/envs/tia37/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/li/.conda/envs/tia37/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/li/.conda/envs/tia37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/li/.conda/envs/tia37/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/home/li/.conda/envs/tia37/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/li/.conda/envs/tia37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/li/.conda/envs/tia37/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/li/.conda/envs/tia37/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/li/.conda/envs/tia37/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 69, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/home/li/.conda/envs/tia37/lib/python3.7/subprocess.py", line 328, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/data/li/One-Thing-One-Click/3D-U-Net/lib/spconv', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/li/One-Thing-One-Click/3D-U-Net/lib/spconv/build/lib.linux-x86_64-3.7/spconv', '-DCMAKE_PREFIX_PATH=/home/li/.conda/envs/tia37/lib/python3.7/site-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.7', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

**Comment by Violetit** [comment]
solved

**Comment by SBXGary** [comment]
> solved

hi, how you solve this issue?
